# Generated by Django 3.1 on 2020-09-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='FIRNumber',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='crimeDescription',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='crimeType',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='dateOfCrime',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='fieldOfInterest',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='officerOnDuty',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='victims',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='criminalID',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='presentPrison',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='previousCrimeRecord',
        ),
    ]
